### ISSUE TITLE
Change html structure

### ISSUE THREAD

**Issue by bordi** [micksle/KPI_Chores#1]
It's better to use `nav > ul > li > a` structure for navigation 

https://github.com/mickzle/KPI_Chores/blob/9acdad6a150c4d9630a4508212a909e986fee84d/3rd%20term/WEB%20design%20and%20technologies/Lab1/index.html#L15

**Comment by micksle** [comment]
@bordi 👋

is it now as it should be? [(lines](https://github.com/mickzle/KPI_Chores/blob/9acdad6a150c4d9630a4508212a909e986fee84d/3rd%20term/WEB%20design%20and%20technologies/Lab1/index.html) 11-21) 

also, should it be used separetely or moved as an independent part inside a `li {...}` css style?
 ```
<header class="main">
            <img src="C:\Users\mickle\Desktop\WEB\images\logo1.jpg" class="logo">
            <div class="title">MICKZLE`S PRODUCT</div>
	    <nav style="margin-left: 550px;">
                <ul>
                    <li style="display:inline-block;"><a href="index.html#main" class="navigation">ABOUT</a></li>
                    <li style="display:inline-block;"><a href="index.html#participants" class="navigation">PARTICIPANTS</a></li>
                    <li style="display:inline-block;"><a href="index.html#contacts" class="navigation">CONTACTS</a></li>
                </ul>
	     </nav>
</header>
```

## **PREVIEW:** 
![image](https://user-images.githubusercontent.com/109234959/199025720-ce61030d-ef25-4d23-bcdc-10b05229ef9b.png)

**Comment by bordi** [comment]
It's ok now.
 

Regarding your question - the rule is simply as fuck 😀: if you do have css file, all styles, for now, should be listed there.
It will be much easier to change something rather go to html/css files every time

**Comment by micksle** [comment]
i got you, then i`ll transfer it to the css file, thanks for the help! all the best🫡
